# Word Embeddings

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

The indices of the words represent the values in the look up table

In [2]:
word_to_idx = {"I":0, "love":1, "eating":2, "and":3,"sleeping":4}

nn.Embeddings(words_in_vocab, embedding size)

In [3]:
embeddings = nn.Embedding(5, 7) 

In [4]:
word_index = torch.tensor([word_to_idx["love"]])
print(word_index)

tensor([1])


Running Embedding

In [5]:
love = embeddings(word_index)

In [6]:
print(love)
print(love.shape)

tensor([[ 0.7536, -1.7540, -1.1920,  0.4188, -0.6679, -0.2540, -1.0627]],
       grad_fn=<EmbeddingBackward>)
torch.Size([1, 7])


In [8]:
all_ind = torch.tensor([w for w in range(5)], dtype=torch.long)
all_words = embeddings(all_ind)
print(all_words)
print(all_words.shape)

tensor([[-1.0435,  1.2275,  0.1159,  0.7221, -0.9739, -1.5204,  1.3203],
        [ 0.7536, -1.7540, -1.1920,  0.4188, -0.6679, -0.2540, -1.0627],
        [-0.1224, -0.6746,  0.5554,  1.1343, -0.2968,  1.5896,  0.6865],
        [ 1.3464,  1.6650,  0.5429,  0.1088, -1.0269,  0.0239, -0.2477],
        [-1.2609, -1.0386,  0.8509, -0.1361,  0.0403, -0.6525, -0.7994]],
       grad_fn=<EmbeddingBackward>)
torch.Size([5, 7])


## Exercise : N-Gram Skip Model