In [2]:
import torch

# Torch Tensors

Creating 1D Tensor

In [3]:
a = torch.tensor([2,2,1])

In [4]:
print(a)

tensor([2, 2, 1])


Creating 2D Tensor

In [5]:
b = torch.tensor([[2,1,4],[3,5,4],[3,5,4],[1,2,0],[4,3,2]])

In [6]:
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


The size(shape) of the tensor

In [7]:
print(a.shape)
print(a.size())
print(b.shape)
print(b.size())

torch.Size([3])
torch.Size([3])
torch.Size([5, 3])
torch.Size([5, 3])


Number of rows (Height) of tensor b

In [8]:
print(b.shape[0])

5


Creating tensors with different data types

In [9]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[3,5,4],[1,2,0],[4,3,2]])

In [10]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[3,5,4],[1,2,0],[4,3,2]])

In [11]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [12]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [13]:
print(c.mean())

tensor(2.8667)


In [14]:
print(d.mean())

tensor(2.8667, dtype=torch.float64)


In [15]:
print(c.std())

tensor(1.5055)


In [19]:
print(d.std())
print(d[0].std())
print(d[0].mean())

tensor(1.5055, dtype=torch.float64)
tensor(1.5275, dtype=torch.float64)
tensor(2.3333, dtype=torch.float64)


**Reshape B**<br/>
Note : If one of the dimensions is -1, its size can be inferred

In [21]:
b

tensor([[2, 1, 4],
        [3, 5, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])

In [23]:
print(b.view(-1,1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])


In [26]:
print(b.view(15))

tensor([2, 1, 4, 3, 5, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])


In [29]:
print(b.view(-1,5))

tensor([[2, 1, 4, 3, 5],
        [4, 3, 5, 4, 1],
        [2, 0, 4, 3, 2]])


In [30]:
print(b.view(3,5))

tensor([[2, 1, 4, 3, 5],
        [4, 3, 5, 4, 1],
        [2, 0, 4, 3, 2]])


assigning **b** a new shape

In [31]:
new_b = b.view(1,-1)

In [32]:
new_b

tensor([[2, 1, 4, 3, 5, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])

In [33]:
new_b.shape

torch.Size([1, 15])

Creating a 3D Tensor with 2 channels, 3 rows, and 4 columns <br/>
randn(channels, rows, columns) -> Normal Distribution<br/>
rand(channels, rows, columns) -> Numbers between 0 and 1

In [34]:
three_dim = torch.randn(2,3,4)

In [35]:
three_dim

tensor([[[-0.8533,  1.7769,  0.0439,  0.0621],
         [ 0.0584, -0.5222, -0.1601,  0.8640],
         [-0.0956,  0.4816,  1.0009, -1.3629]],

        [[-1.3700, -0.1155,  1.0965, -0.5082],
         [-0.5940,  0.8681, -0.6196, -1.0638],
         [ 0.0184,  1.4215,  1.7270, -0.8043]]])

In [36]:
three_dim.shape

torch.Size([2, 3, 4])

In [37]:
three_dim.view(2,12)

tensor([[-0.8533,  1.7769,  0.0439,  0.0621,  0.0584, -0.5222, -0.1601,  0.8640,
         -0.0956,  0.4816,  1.0009, -1.3629],
        [-1.3700, -0.1155,  1.0965, -0.5082, -0.5940,  0.8681, -0.6196, -1.0638,
          0.0184,  1.4215,  1.7270, -0.8043]])

In [38]:
three_dim.view(2,-1)

tensor([[-0.8533,  1.7769,  0.0439,  0.0621,  0.0584, -0.5222, -0.1601,  0.8640,
         -0.0956,  0.4816,  1.0009, -1.3629],
        [-1.3700, -0.1155,  1.0965, -0.5082, -0.5940,  0.8681, -0.6196, -1.0638,
          0.0184,  1.4215,  1.7270, -0.8043]])

In [39]:
r2 = torch.rand(4,4)

In [40]:
print(r2)
print(r2.shape)

tensor([[0.1250, 0.2081, 0.0235, 0.0073],
        [0.6555, 0.4820, 0.9321, 0.0339],
        [0.9497, 0.8656, 0.1490, 0.0897],
        [0.8870, 0.6227, 0.1429, 0.6822]])
torch.Size([4, 4])


In [41]:
r2 - 3

tensor([[-2.8750, -2.7919, -2.9765, -2.9927],
        [-2.3445, -2.5180, -2.0679, -2.9661],
        [-2.0503, -2.1344, -2.8510, -2.9103],
        [-2.1130, -2.3773, -2.8571, -2.3178]])

**Creating an array of 5 random integers from values between 6 and 9**<br/>
randint(start, end + 1, shape)

In [46]:
ran_arr = torch.randint(6,10, (5,1)) # this excludes 10

In [48]:
print(ran_arr)
print(ran_arr.dtype)

tensor([[6],
        [8],
        [6],
        [8],
        [8]])
torch.int64


constructing zero matrix

In [50]:
z = torch.zeros(3,3,dtype=torch.long)

In [51]:
z

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [52]:
o = torch.ones(3,3,dtype=torch.long)

In [53]:
o
o.dtype

torch.int64

Convert the data type of the tensor

In [54]:
r2

tensor([[0.1250, 0.2081, 0.0235, 0.0073],
        [0.6555, 0.4820, 0.9321, 0.0339],
        [0.9497, 0.8656, 0.1490, 0.0897],
        [0.8870, 0.6227, 0.1429, 0.6822]])

In [56]:
r2_like = torch.randn_like(r2, dtype=torch.double)
print(r2_like)

tensor([[ 0.3616,  1.2645,  0.3067,  1.2190],
        [-0.3856,  0.1827, -0.0720, -0.2668],
        [ 0.4284, -0.3940, -1.1863,  1.2514],
        [-0.0625,  1.2441, -0.8051,  0.5137]], dtype=torch.float64)


**Math Operations**

In [61]:
add_result = torch.add(r2, r2_like)
add_result2 = r2+r2_like
# modifying it directly
r2.add_(r2_like)

tensor([[ 0.4865,  1.4725,  0.3302,  1.2263],
        [ 0.2699,  0.6647,  0.8601, -0.2329],
        [ 1.3781,  0.4715, -1.0372,  1.3411],
        [ 0.8245,  1.8669, -0.6622,  1.1959]])

In [62]:
print(r2)
print(add_result)
print(add_result2)

tensor([[ 0.4865,  1.4725,  0.3302,  1.2263],
        [ 0.2699,  0.6647,  0.8601, -0.2329],
        [ 1.3781,  0.4715, -1.0372,  1.3411],
        [ 0.8245,  1.8669, -0.6622,  1.1959]])
tensor([[ 0.4865,  1.4725,  0.3302,  1.2263],
        [ 0.2699,  0.6647,  0.8601, -0.2329],
        [ 1.3781,  0.4715, -1.0372,  1.3411],
        [ 0.8245,  1.8669, -0.6622,  1.1959]], dtype=torch.float64)
tensor([[ 0.4865,  1.4725,  0.3302,  1.2263],
        [ 0.2699,  0.6647,  0.8601, -0.2329],
        [ 1.3781,  0.4715, -1.0372,  1.3411],
        [ 0.8245,  1.8669, -0.6622,  1.1959]], dtype=torch.float64)


**Matrix Slicing**

In [63]:
r2

tensor([[ 0.4865,  1.4725,  0.3302,  1.2263],
        [ 0.2699,  0.6647,  0.8601, -0.2329],
        [ 1.3781,  0.4715, -1.0372,  1.3411],
        [ 0.8245,  1.8669, -0.6622,  1.1959]])

In [65]:
r2[:, 1] # all the rows and 2nd item only

tensor([1.4725, 0.6647, 0.4715, 1.8669])

In [66]:
r2[:, :2] # all the rows and first and second columns only

tensor([[0.4865, 1.4725],
        [0.2699, 0.6647],
        [1.3781, 0.4715],
        [0.8245, 1.8669]])

In [67]:
r2.items()

AttributeError: 'Tensor' object has no attribute 'items'

In [68]:
num_tem = r2[2,3]

In [69]:
num_tem

tensor(1.3411)

In [70]:
num_tem.item()

1.3410924673080444

**Numpy Bridge**

In [71]:
import numpy as np

In [72]:
a = torch.randn(2,3)

In [73]:
print(a)

tensor([[ 0.9941,  0.5548, -0.4832],
        [-1.3409, -0.6631, -0.4539]])


In [74]:
b = a.numpy()

In [75]:
b

array([[ 0.99410015,  0.55481493, -0.48324597],
       [-1.3408574 , -0.66314137, -0.45390543]], dtype=float32)

In [76]:
a.add_(3) # This also effects the numpy number

tensor([[3.9941, 3.5548, 2.5168],
        [1.6591, 2.3369, 2.5461]])

In [77]:
b

array([[3.9941   , 3.5548148, 2.5167542],
       [1.6591426, 2.3368587, 2.5460947]], dtype=float32)