# Automatic Differentiation

Remember, if requires_grad =True, the tensor object keeps track of how it was created.

In [2]:
import torch

In [3]:
x = torch.tensor([1.,2.,3.], requires_grad=True)
y = torch.tensor([4.,5.,6.], requires_grad=True)

Notice that both x and y have their "required_grad" set to true, therefore we can compute gradients with respect to them

In [4]:
z = x + y 

In [5]:
print(z)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)


We can track that it was created as a result of addition of x and y. It knows that it wasn't read in from a file

In [6]:
print(z.grad_fn)

And If we go further on this

In [7]:
s = z.sum()

In [8]:
print(s)

tensor(21., grad_fn=<SumBackward0>)


In [9]:
print(s.grad_fn)

Now if we backpropagate on s, we can find the gradients of s with respect to x

In [10]:
s.backward()

In [11]:
x.grad

tensor([1., 1., 1.])

By default, Tensors have `requires_grad=False`

In [12]:
x = torch.randn(2,2)
y = torch.randn(2,2)
print(x.requires_grad, y.requires_grad)

False False


In [13]:
z = x + y

So you can't back propagate through z

In [14]:
print(z.grad_fn)

None


Another way to set the `requires_grad=True` is

In [15]:
x.requires_grad_()
y.requires_grad_()

tensor([[ 1.1409, -0.3071],
        [-0.3525,  0.5636]], requires_grad=True)

In [16]:
z = x + y
print(z.grad_fn)

Now z has the computation history that relates itself to x and y<br/><br/>
**detach()** returns a tensor that shares the same storage as `z`, but with the computation history forgotten.<br>
It doesn't know anything about how it was computed. In other words, we have broken the Tensor away from its past history

In [17]:
new_z = z.detach()
print(new_z.grad_fn)

None


You can also stop autograd from tracking history on Tensors. This concept is useful when applying Transfer Learning

In [18]:
print(x.requires_grad)

True


In [19]:
print((x+10).requires_grad)

True


In [22]:
with torch.no_grad():
    print((x+10).requires_grad)
    print(x.requires_grad)

False
True


Let's walk in through one last example


In [23]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [24]:
y = x + 2

In [25]:
print(y.requires_grad)

True


In [26]:
print(y.grad_fn)

In [27]:
z = y * y * 3

In [28]:
out = z.mean()

In [29]:
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [30]:
out.backward()

In [32]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [34]:
print(y.grad)

None
